#### CORE PYTHON LIBRARIES USED FOR ML

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [20]:
# NumPy is used for mathematical computing/operations. (creating arrays, basic maths, Statistics)
# Pandas is used for data handling(cleaning), data manipulation, creating tables, creating Dataframes (CSV Files)
# Matplotlib is used for visualizing data in the form of graphs and charts.(piechart,bargraph,histogram,lineplot,scatterplot,boxplot)
# Sklearn is the library used for machine learning and there are various modules present in it.
# Model_selection is a module which also has several modules in it.
# train_test_split is a module used for training and testing sets.
# Preprocessing is also a module which also has several modules.


# StandardScaler is used to scale data (mean = 0, standard_deviation = 1).
# In machine learning, we have to choose the dataset which is normally distributed.
# When we have large datasets, the data is supposed to be normal plus non-normal, so as to convert the dataset into normally distributed data we use standard scaler.
# We need normally distributed data because the machine learning and AI algos best work on normally distributed data.


# Accuracy score, Precision score, recall_score, and f1_score are used evaluate classification models.

#### Algorithms with proper definitions and codes

#### Linear Regression (House Price Prediction)

In [23]:
# Definition: Linear regression is a supervised learning algorithm used to predict a continuos value.
# It finds the best fit-straight line.
# y = mx + c
# Where y = output (Dependent), x = input (Independent)
# y will be the price of the house whereas x will be the area of the house.

#  Area     |       Price
#  2000     |      10000$
#  4000      |     20000$
#  1000     |      5000 $

# What will be the price if the area if 20000 sq feet

from sklearn.linear_model import LinearRegression
# Linear model is a module which contains the module linear regression
# Imports Linear Regression algorithm

In [24]:
data = {
    'size_sqft' : [800,100,1200,1500,1800],
    'Price' : [40,50,60,75,90]
}

# Created a dataset
# size_sqft: Input feature (x-axis)
# Price: Output label (y-axis)

df = pd.DataFrame(data)
# Converts dictionary into dataframe
df

   size_sqft  Price
0        800     40
1        100     50
2       1200     60
3       1500     75
4       1800     90

In [25]:
X = df[['size_sqft']]
# Feature Matrix (2-D)
y = df['Price']
# Target / Output Variable

In [26]:
model = LinearRegression()
# Create a Linear Regression ALgorithm

In [27]:
model.fit(X,y)
# Trains the model by learning the relationship between X and y

LinearRegression()

In [28]:
model.predict([[20000]])
# Predicts house price at 20000 sqft to 531k $

C:\Users\Shree\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([531.67048055])

In [29]:
# Create a dataset with temperature as input feature and rainfall as output label.
# Use linear regression to predict the values

#### RAINFALL PREDICTION

In [31]:
data = {
    'temperature' : [25,20,15,18,12],
    'Rainfall_mm' : [17,20,22,20.5,25]
}

df = pd.DataFrame(data)

In [32]:
X = df[['temperature']]
y = df['Rainfall_mm']

In [33]:
model = LinearRegression()

In [34]:
model.fit(X,y)

LinearRegression()

In [35]:
model.predict([[30]])

C:\Users\Shree\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([13.92040816])

#### LOGISTIC REGRESSION

In [53]:
# Logistic regression is an algorithm based on supervised learning. It is used for binary classification.
# Binary classification means the output has only two possible classes.

In [55]:
# Examples: Spam email(1) or Not spam (0)
# Disease (Yes/No)
# Pass/Fail

In [57]:
# The name contains regression, but logistic regression is a classification algorithm.

In [59]:
# Why it is needed.?
# Linear regression is not suitable for classification because:
# It can only predict values which are less than 0 or greater than 1.
# Classification requires probability (0 and 1)

## Logistic regression solves these type of problems using sigmoid function

In [61]:
## Sigmoid Function
# It converts any real value into a number between 0 and 1.
# Output is represented as probability
# Example: Output is 0.8 - > 80% chance of disease, 80% chance of receiving spam message
# Output is 0.2 ->20 % chance of disease, 20% chance of spam messages

In [65]:
from sklearn.linear_model import LogisticRegression
# Imports Logistic Regression classifier from scikit-learn

In [69]:
data = {
    'Study_Hours' : [1,2,3,4,5,6,7,8],
    'Pass' : [0,0,0,0,1,1,1,1]
}
# Study_hours: Input Features(X)
# Pass: Output Label (y)

df = pd.DataFrame(data)
df
# Converts dictionary into dataframe

   Study_Hours  Pass
0            1     0
1            2     0
2            3     0
3            4     0
4            5     1
5            6     1
6            7     1
7            8     1

In [71]:
# Seperate Features and targets
X = df[['Study_Hours']]
y = df['Pass']

# X: Feature Matrix
# y: target variable

In [73]:
# Creating a model
model = LogisticRegression()

In [75]:
# Trains the model
model.fit(X,y)

LogisticRegression()

In [79]:
# Predicting the value
model.predict([[-2]])

C:\Users\Shree\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [81]:
# Predict whether the email will be spam or ham based on the length of the mail
# Use logistic Regression

#### EMAIL SPAM DETECTION

In [83]:
data = {
    'Length_email' : [20,30,40,50,45,25,65,75,85,95,15],
    'Spam': [0,0,0,1,0,0,1,1,1,1,0]
}

df = pd.DataFrame(data)
df.head()

   Length_email  Spam
0            20     0
1            30     0
2            40     0
3            50     1
4            45     0

In [85]:
# Take the features and the labels
X = df[['Length_email']] # Input feature
y = df['Spam'] # Output Label

In [87]:
model = LogisticRegression() # Created a Logistic Regression model

In [89]:
model.fit(X,y) # Train the spam classification model

LogisticRegression()

In [95]:
# Predict the value
model.predict([[55]])

C:\Users\Shree\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1], dtype=int64)