In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
ins=pd.read_csv('insurance.csv')
ins.head()

   index  age     sex     bmi  children smoker     region      charges
0      0   19  female  27.900         0    yes  southwest  16884.92400
1      1   18    male  33.770         1     no  southeast   1725.55230
2      2   28    male  33.000         3     no  southeast   4449.46200
3      3   33    male  22.705         0     no  northwest  21984.47061
4      4   32    male  28.880         0     no  northwest   3866.85520

In [16]:
ins.info()
ins.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             1338 non-null   int64
 1   age               1338 non-null   int64
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64
 4   charges           1338 non-null   float64
 5   sex_male          1338 non-null   bool
 6   smoker_yes        1338 non-null   bool
 7   region_northwest  1338 non-null   bool
 8   region_southeast  1338 non-null   bool
 9   region_southwest  1338 non-null   bool
dtypes: bool(5), float64(2), int64(3)
memory usage: 58.9 KB

index               0
age                 0
bmi                 0
children            0
charges             0
sex_male            0
smoker_yes          0
region_northwest    0
region_southeast    0
region_southwest    0
dtype: int64

In [15]:
ins = pd.get_dummies(ins, columns=['sex', 'smoker', 'region'], drop_first=True)
ins.head()

,index,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,0,19,27.900,0,16884.92400,False,True,False,False,True
1,1,18,33.770,1,1725.55230,True,False,False,True,False
2,2,28,33.000,3,4449.46200,True,False,False,True,False
3,3,33,22.705,0,21984.47061,True,False,True,False,False
4,4,32,28.880,0,3866.85520,True,False,True,False,False

In [24]:
x = ins.drop('charges', axis=1)

y = ins['charges']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [25]:
model = LinearRegression()

In [26]:
model.fit(x_train,y_train)

LinearRegression()

In [28]:
y_pred=model.predict(x_test)

In [29]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Absolute Error: 4239.271070660337
Mean Squared Error: 39210080.50511915
R-squared: 0.7400335372014808